In [77]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

In [78]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import GridSearchCV
from sklearn import svm

In [79]:
from sklearn.model_selection import train_test_split

In [80]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score,recall_score,confusion_matrix

In [81]:
#Import the Dataset
df= pd.read_csv("../dataset/English-ONLY.csv")
df.head()

                                          email_text      email_type
0  Hello I am your hot lil horny toy.\n    I am t...  Phishing Email
1  On Sun, Aug 11, 2002 at 11:17:47AM +0100, wint...      Safe Email
2  URL: http://www.newsisfree.com/click/-5,830431...      Safe Email
3  begin forwarded text Date: Wed, 25 Sep 2002 13...      Safe Email
4  The academic discipline of Software Engineerin...      Safe Email

In [82]:
df.isna().sum()

email_text    0
email_type    0
dtype: int64

In [83]:
#Drop tha Na values
df = df.dropna()
print(df.isna().sum())

email_text    0
email_type    0
dtype: int64

In [84]:
df.shape

(1484, 2)

In [85]:
# Count the occurrences of each E-mail type. 
email_type_counts = df['email_type'].value_counts()
print(email_type_counts)

email_type
Safe Email        1232
Phishing Email     252
Name: count, dtype: int64

In [86]:
# # We will use undersapling technique 
Safe_Email = df[df["email_type"]== "Safe Email"]
Phishing_Email = df[df["email_type"]== "Phishing Email"]
Safe_Email = Safe_Email.sample(Phishing_Email.shape[0])

In [87]:
# lets check the sahpe again 
Safe_Email.shape,Phishing_Email.shape

((252, 2), (252, 2))

In [88]:
# lest create a new Data with the balanced E-mail types
Data= pd.concat([Safe_Email, Phishing_Email], ignore_index = True)
Data.head()

                                          email_text  email_type
0  I'm after a recipe for using Razor with Sendma...  Safe Email
1  Update of /cvsroot/spamassassin/spamassassin/l...  Safe Email
2  > Date: Mon, 30 Sep 2002 14:00:12 -0400 (EDT)\...  Safe Email
3  James> This is not an exmh problem, but an int...  Safe Email
4  Maybe I'm just blind, but I've been poking thr...  Safe Email

In [89]:
# split the data into a metrix of features X and Dependent Variable y
X = Data["email_text"].values
y = Data["email_type"].values

In [90]:
#split the dataset
x_train, x_test, y_train, y_test = train_test_split( X, y, test_size = 0.3, random_state=0)

In [91]:
cv = CountVectorizer() 
x_train = cv.fit_transform(x_train)
x_test = cv.transform(x_test)

In [92]:
#C, kernel and gamma are hyperparameters
model = SVC(random_state = 0, C = 100, gamma = 0.1) 
model.fit(x_train, y_train)

SVC(C=100, gamma=0.1, random_state=0)

In [93]:
y_pred = model.predict(x_test)

In [76]:
# Model Accuracy
# record accuracy in file
with open("svm_model_accuracy.txt", "a") as file:
    file.write(f"\n Model Accuracy: {accuracy_score(y_test, y_pred):.2f}\n Precision: {precision_score(y_test, y_pred,pos_label='Phishing Email'):.2f}\n Recall: {recall_score(y_test, y_pred,pos_label='Phishing Email'):.2f}\n Confusion matrix:\n{confusion_matrix(y_test,y_pred)}")